project:
  type: website

website:
  title: "CSM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
    toc: true



